In [1]:
import numpy as np

In [2]:
arr = np.array([[[1,2,3],[7,8,9]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
np.ndim(arr)

3

In [3]:
arr.shape

(3, 2, 3)

In [4]:
arr.dtype

dtype('int32')

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr = np.array([[[1,2,3],[7,8,9]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],dtype='int')


In [7]:
arr.dtype

dtype('int32')

In [8]:
np.zeros((3,3,3),dtype='int')

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [9]:
np.full((3,3),5,dtype='complex')

array([[5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j],
       [5.+0.j, 5.+0.j, 5.+0.j]])

In [10]:
shape = (3, 3)  # Shape of the array
complex_value = 2 + 3j  # The complex value to fill the array with
complex_array = np.full(shape, complex_value, dtype=complex)
complex_array

array([[2.+3.j, 2.+3.j, 2.+3.j],
       [2.+3.j, 2.+3.j, 2.+3.j],
       [2.+3.j, 2.+3.j, 2.+3.j]])

In [11]:
np.random.random((3,3,2,4))

array([[[[0.38669495, 0.21907331, 0.48975982, 0.47403078],
         [0.62719717, 0.33323303, 0.0024663 , 0.81360814]],

        [[0.54878494, 0.70606492, 0.77037769, 0.1056277 ],
         [0.56283319, 0.3747303 , 0.87443584, 0.91036766]],

        [[0.97833645, 0.09143304, 0.06745385, 0.43739476],
         [0.92771168, 0.3509184 , 0.26855895, 0.81636576]]],


       [[[0.99617891, 0.63103286, 0.31834132, 0.88136645],
         [0.53289625, 0.00107602, 0.97526387, 0.40357748]],

        [[0.35122557, 0.82224389, 0.82561106, 0.27549027],
         [0.25543854, 0.96786467, 0.61889768, 0.57349673]],

        [[0.07514959, 0.62066508, 0.69830472, 0.70556845],
         [0.6629133 , 0.03604173, 0.26283974, 0.87511581]]],


       [[[0.75124517, 0.51779953, 0.73123517, 0.14668768],
         [0.21638188, 0.47165719, 0.25470695, 0.65776701]],

        [[0.71386996, 0.26017017, 0.89586456, 0.35719737],
         [0.25389885, 0.51637754, 0.72738664, 0.77358217]],

        [[0.34815232, 0.498577  , 0.

In [12]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [13]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [14]:
np.linspace(0,2*np.pi,10)

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [15]:
arr.flatten()

array([1, 2, 3, 7, 8, 9, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [16]:
arr1 =  np.random.random((3,3,2,4))
temp = arr1[:2,::2,::1,::2]
temp

array([[[[0.35864131, 0.470505  ],
         [0.95599764, 0.56834086]],

        [[0.17404649, 0.9340453 ],
         [0.05778034, 0.36272682]]],


       [[[0.68495084, 0.91769219],
         [0.7346528 , 0.92144239]],

        [[0.49209375, 0.729098  ],
         [0.76119739, 0.26076751]]]])

In [17]:
import numpy as np

# Create a 4D array (shape: 2x3x4x5)
four_d_array = np.arange(2*3*4*5).reshape(2, 3, 4, 5)

# Access specific elements using integer indexing
element_0_1_2_3 = four_d_array[0, 1, 2, 3]  # Access element at index (0, 1, 2, 3)
element_1_2_2_4 = four_d_array[1, 2, 2, 4]  # Access element at index (1, 2, 2, 4)

print("Element at (0, 1, 2, 3):", element_0_1_2_3)
print("Element at (1, 2, 2, 4):", element_1_2_2_4)

# Access slices of the 4D array using integer indexing
slice_0_2 = four_d_array[0, :, 2, :]  # Access slice at index (0, :, 2, :)
slice_1_1 = four_d_array[1, 1, :, :]  # Access slice at index (1, 1, :, :)

print("\nSlice at (0, :, 2, :):\n", slice_0_2)
print("\nSlice at (1, 1, :, :):\n", slice_1_1)


Element at (0, 1, 2, 3): 33
Element at (1, 2, 2, 4): 114

Slice at (0, :, 2, :):
 [[10 11 12 13 14]
 [30 31 32 33 34]
 [50 51 52 53 54]]

Slice at (1, 1, :, :):
 [[80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]


In [18]:
four_d_array


array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [19]:
con = four_d_array>25
temp = four_d_array[con]
temp

array([ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [20]:
four_d_array.T

array([[[[  0,  60],
         [ 20,  80],
         [ 40, 100]],

        [[  5,  65],
         [ 25,  85],
         [ 45, 105]],

        [[ 10,  70],
         [ 30,  90],
         [ 50, 110]],

        [[ 15,  75],
         [ 35,  95],
         [ 55, 115]]],


       [[[  1,  61],
         [ 21,  81],
         [ 41, 101]],

        [[  6,  66],
         [ 26,  86],
         [ 46, 106]],

        [[ 11,  71],
         [ 31,  91],
         [ 51, 111]],

        [[ 16,  76],
         [ 36,  96],
         [ 56, 116]]],


       [[[  2,  62],
         [ 22,  82],
         [ 42, 102]],

        [[  7,  67],
         [ 27,  87],
         [ 47, 107]],

        [[ 12,  72],
         [ 32,  92],
         [ 52, 112]],

        [[ 17,  77],
         [ 37,  97],
         [ 57, 117]]],


       [[[  3,  63],
         [ 23,  83],
         [ 43, 103]],

        [[  8,  68],
         [ 28,  88],
         [ 48, 108]],

        [[ 13,  73],
         [ 33,  93],
         [ 53, 113]],

        [[ 18,  78]

In [21]:
four_d_array.max(axis=0
)

array([[[ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79]],

       [[ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119]]])

In [22]:
np.sum(four_d_array,axis=1)

array([[[ 60,  63,  66,  69,  72],
        [ 75,  78,  81,  84,  87],
        [ 90,  93,  96,  99, 102],
        [105, 108, 111, 114, 117]],

       [[240, 243, 246, 249, 252],
        [255, 258, 261, 264, 267],
        [270, 273, 276, 279, 282],
        [285, 288, 291, 294, 297]]])

In [23]:
np.sort(four_d_array,axis=0)

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [24]:
four_d_array[:-1,::-1,::-1,::-1]

array([[[[59, 58, 57, 56, 55],
         [54, 53, 52, 51, 50],
         [49, 48, 47, 46, 45],
         [44, 43, 42, 41, 40]],

        [[39, 38, 37, 36, 35],
         [34, 33, 32, 31, 30],
         [29, 28, 27, 26, 25],
         [24, 23, 22, 21, 20]],

        [[19, 18, 17, 16, 15],
         [14, 13, 12, 11, 10],
         [ 9,  8,  7,  6,  5],
         [ 4,  3,  2,  1,  0]]]])

In [25]:
iterable = (x*x for x in range(8))
np.fromiter(iterable,dtype = 'float',count=-1)

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [26]:
np.empty((2,3),dtype='str',order = 'c')

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [27]:
from functools import reduce

In [28]:
array = reduce(np.union1d,([1,2,3],[2,3,1],[2,4,6],[0,0,0]))
array

array([0, 1, 2, 3, 4, 6])

In [31]:
np.trim_zeros(array,'f')

array([1, 2, 3, 4, 6])

In [34]:
np.eye(3,4,k=0,dtype='float',order= 'c')

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [35]:
import numpy.matlib

In [39]:
np.matlib.identity(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [42]:
np.eye(5,5,k=-2) @ np.matlib.identity(5) 


matrix([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

In [43]:
from numpy import linalg as la

In [45]:
la.eigvals([[1,2],[3,4]])

array([-0.37228132,  5.37228132])

In [46]:
import numpy as np

# Create an array of data
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Calculate the peak-to-peak range
range_value = np.ptp(data)

print("Data:", data)
print("Peak-to-Peak Range:", range_value)


Data: [10 20 30 40 50 60 70 80 90]
Peak-to-Peak Range: 80


In [49]:
def fun(val):
    return (val**2)

power = np.frompyfunc(fun,1,1)
arr = np.arange(1,11,1)
mod_arr = power(arr)
mod_arr

array([1, 4, 9, 16, 25, 36, 49, 64, 81, 100], dtype=object)